// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqjriuhgbteiocsjdvwg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxanJpdWhnYnRlaW9jc2pkdndnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0OTY1NTAsImV4cCI6MjA3MjA3MjU1MH0.b-ASH7aTZ82TdRhE0UqeiIFXGZDQjPBvbyn6cjGSIEQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});